Repository 2025-CapstoneDesign/Unity, pull requests merged in 2025-05, with the labels that each got.

#21 Fix/aed
  Assets/Scenes/AEDScene.unity
  Assets/Scripts/NoticeMenu/SceneStartGuide.cs
  Assets/Scripts/Test/TestAEDManager.cs
  Assets/Scripts/Timer/TimerManager.cs
Labels: bug

#22 Feat/create manager v2
  Assets/Scenes/AEDScene.unity
  Assets/Scenes/Test/RefactorAEDScene.unity
  Assets/Scripts/Common/BaseUIManager.cs
  Assets/Scripts/Interfaces/IUIManager.cs
  Assets/Scripts/NoticeMenu/SceneStartGuide.cs
  Assets/Scripts/Sensor/BreathValidator.cs
  Assets/Scripts/Sensor/CPRValidator.cs
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Test/TestAEDManager.cs
  Assets/Scripts/Timer/TimerManager.cs
Labels: bug

#24 Feat/trauma patient
  Assets/Scenes/FeedbackScene.unity
  Assets/Scenes/TraumaPatientAssessment.unity
  Assets/Scenes/TraumaPatientAssessment.unity.meta
  Assets/Scripts/Feedback/FeedbackManager.cs
  Assets/Scripts/Feedback/FeedbackUIController.cs
  Assets/Scripts/Feedback/FeedbackUIController.cs.meta
  Assets/Scripts/Game/GameManager.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentManager.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentMessageManager.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentState.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentState.cs.meta
  Assets/Scripts/Test/TestAEDManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#25 Feat/protocol any
  Assets/Scripts/Stage/InfantAirway/InfantAirwayManager.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayToErrorType.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayUIManager.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayUIManager.cs.meta
  Assets/Scripts/Stage/InfantCPR/InfantCPRManager.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRToErrorType.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRUIManager.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRUIManager.cs.meta
  Assets/Scripts/Stage/SpinialMotionRestriction/SpinialMotionRestrictionManager.cs
  Assets/Scripts/Stage/SpinialMotionRestriction/SpinialMotionRestrictionUIManager.cs
  Assets/Scripts/Stage/SpinialMotionRestriction/SpinialMotionRestrictionUIManager.cs.meta
  Assets/Scripts/Stage/Suction/SuctionManager.cs
  Assets/Scripts/Stage/Suction/SuctionUIManager.cs
  Assets/Scripts/Stage/Suction/SuctionUIManager.cs.meta
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintManager.cs
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintToErrorType.cs
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintUIManager.cs
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintUIManager.cs.meta
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentToErrorType.cs
  Assets/Scripts/Stage/VaccumSplint/VaccumSplintManager.cs
  Assets/Scripts/Stage/VaccumSplint/VaccumSplintUIManager.cs
  Assets/Scripts/Stage/VaccumSplint/VaccumSplintUIManager.cs.meta
  Assets/Scripts/Stage/VaccumSplint/VacuumSplintToErrorType.cs
  Assets/Scripts/Test/TestAEDManager.cs
Labels: enhancement

#28 chore: paste TestAEDManager in AEDManager
  Assets/Scenes/AEDScene.unity
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Stage/AED/AEDSceneStart.cs
Labels: invalid, del

#29 fix: 누락된 음성 상태 전달 메서드 추가
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayManager.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRManager.cs
  Assets/Scripts/Stage/Suction/SuctionManager.cs
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintManager.cs
  Assets/Scripts/Stage/VaccumSplint/VaccumSplintManager.cs
Labels: bug

#30 feat: 센서 검증 성인 및 유아 분리 및 getter 방식으로 변경
  Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityDiagnosticsProfile.asset
  Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityDiagnosticsProfile.asset.meta
  Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityToolkitConfigurationProfile.asset
  Assets/Scenes/AEDScene.unity
  Assets/Scripts/Sensor/BreathValidator.cs
  Assets/Scripts/Sensor/CPRValidator.cs
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayManager.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRManager.cs
  Assets/Scripts/Stage/Suction/SuctionManager.cs
  Assets/Scripts/Stage/TractionSplintApplication/TractionSplintManager.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentManager.cs
  Assets/Scripts/Stage/VaccumSplint/VaccumSplintManager.cs
  Assets/Scripts/Test/TestAEDManager.cs
  Assets/Scripts/Test/TestAEDManager.cs.meta
  Assets/Scripts/UI/GradationBarUI.cs
Labels: enhancement

#31 feat: 무브넷 인증 웹소켓 기능 추가
  Assets/Scenes/NetworkScene.unity
  Assets/Scripts/Network/MovenetSocketClient.cs
  Assets/Scripts/Network/MovenetSocketClient.cs.meta
  Assets/Scripts/Test/MovenetTest.cs
  Assets/Scripts/Test/MovenetTest.cs.meta
Labels: enhancement

#32 feat: 마커 회전 검증 추가
  Assets/Scripts/Validation/TurnValidation.cs
  Assets/Scripts/Validation/TurnValidation.cs.meta
Labels: enhancement

#33 feat: 음성 단계 수정
  Assets/Prefab/Network/NetworkManager.prefab
  Assets/Scripts/Network/TrainingEvaluator.cs
  Assets/Scripts/Network/VoiceSender.cs
  Assets/Scripts/Network/VoiceWebSocketClient.cs
  Assets/Scripts/Network/VoiceWebSocketClient.cs.meta
  Assets/Scripts/Stage/SpinialMotionRestriction/SpinalMotionRestrictionToErrorType.cs
  Assets/Scripts/Stage/Suction/SuctionToErrorType.cs
Labels: enhancement

#36 feat: ErrorType 수정
  Assets/Scripts/Stage/AED/AEDStateToErrorType.cs
  Assets/Scripts/Stage/InfantAirway/InfantAirwayToErrorType.cs
  Assets/Scripts/Stage/InfantCPR/InfantCPRToErrorType.cs
  Assets/Scripts/Stage/SpinialMotionRestriction/SpinalMotionRestrictionToErrorType.cs
  Assets/Scripts/Stage/Suction/SuctionToErrorType.cs
  Assets/Scripts/Stage/TraumaPatientAssessment/TraumaPatientAssessmentToErrorType.cs
  Assets/Scripts/Stage/VaccumSplint/VacuumSplintToErrorType.cs
Labels: refactor

#38 Feat/warn message
  Assets/Prefab/Warn.meta
  Assets/Prefab/Warn/WarnCanvas.prefab
  Assets/Prefab/Warn/WarnCanvas.prefab.meta
  Assets/Resources/Audio/Warn.meta
  Assets/Resources/Audio/Warn/WarnSound.mp3
  Assets/Resources/Audio/Warn/WarnSound.mp3.meta
  Assets/Scenes/Stage.meta
  Assets/Scenes/Stage/AEDScene.unity
  Assets/Scenes/Stage/AEDScene.unity.meta
  Assets/Scenes/Stage/InfantAirwayScene.unity
  Assets/Scenes/Stage/InfantAirwayScene.unity.meta
  Assets/Scenes/Stage/InfantCPRScene.unity
  Assets/Scenes/Stage/InfantCPRScene.unity.meta
  Assets/Scenes/Stage/SpinialMotionScene.unity
  Assets/Scenes/Stage/SpinialMotionScene.unity.meta
  Assets/Scenes/Stage/SuctionScene.unity
  Assets/Scenes/Stage/SuctionScene.unity.meta
  Assets/Scenes/Stage/TractionSplintApplicationScene.unity
  Assets/Scenes/Stage/TractionSplintApplicationScene.unity.meta
  Assets/Scenes/Stage/TraumaPatientAssessmentScene.unity
  Assets/Scenes/Stage/TraumaPatientAssessmentScene.unity.meta
  Assets/Scenes/Stage/VaccumSplintScene.unity
  Assets/Scenes/Stage/VaccumSplintScene.unity.meta
  Assets/Scripts/Common/BaseUIManager.cs
  Assets/Scripts/Interfaces/IUIManager.cs
  Assets/Scripts/Warn.meta
  Assets/Scripts/Warn/ShowMessageWithSound.cs
  Assets/Scripts/Warn/ShowMessageWithSound.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, design

#41 feat: 보이스 수정 및 핸드트래킹 변경
  Assets/MixedRealityToolkit.Generated/CustomProfiles/EyeTrackerMixedRealityInputSystemProfile.asset
  Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityHandTrackingProfile.asset
  Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityHandTrackingProfile.asset.meta
  Assets/Scenes/Stage/AEDScene.unity
  Assets/Scenes/Test/TestValidationScene.unity
  Assets/Scripts/Network/VoiceSender.cs
  Assets/Scripts/Test/TestValidateManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#42 feat: 현장 안전 확인 추가 및 평가 프롬프트 변경
  Assets/Scenes/Stage/AEDScene.unity
  Assets/Scripts/Network/TrainingEvaluator.cs
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Test/GPTFeedbackGenerator.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#43 Test/0521
  Assets/Scenes/MenuScene.unity
  Assets/Scenes/Stage/AEDScene.unity
  Assets/Scripts/Network/VoiceSender.cs
  Assets/Scripts/Sensor/BreathValidator.cs
  Assets/Scripts/Sensor/CPRValidator.cs
  Assets/Scripts/Stage/AED/AEDManager.cs
Labels: bug

#44 refactor: 마커 검증 위치 및 반응성 조정
  Assets/Scenes/Stage/AEDScene.unity
  Assets/Scripts/Aruco/MarkerData.cs
  Assets/Scripts/Aruco/OptimizedArUcoMarkerDetection.cs
  Assets/Scripts/Stage/AED/AEDManager.cs
  Assets/Scripts/Test/TestValidateManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
